# Generated by Django 2.0.4 on 2018-04-18 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('adresse', models.CharField(max_length=50)),
                ('codePostal', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('Mme', 'Madame'), ('M', 'Monsieur')], max_length=3)),
                ('adresse', models.CharField(max_length=50)),
                ('codePostal', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='evenement',
            unique_together={('titre', 'date')},
        ),
        migrations.AddField(
            model_name='concerner',
            name='fk_evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IronAgileWebApp.Evenement'),
        ),
        migrations.AddField(
            model_name='concerner',
            name='fk_userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='concerner',
            unique_together={('fk_userProfile', 'fk_evenement')},
        ),
    ]
