# Generated by Django 2.0.4 on 2018-04-18 09:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IronAgileWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerner',
            name='date_inscriptions',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 4, 18, 9, 52, 9, 531143, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
