# Generated by Django 2.0.2 on 2018-04-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IronAgileWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('adresse', models.CharField(max_length=50)),
                ('codePostal', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='evenement',
            unique_together={('titre', 'date')},
        ),
        migrations.AddField(
            model_name='concerner',
            name='fk_evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IronAgileWebApp.Evenement'),
        ),
        migrations.AddField(
            model_name='concerner',
            name='fk_userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IronAgileWebApp.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='concerner',
            unique_together={('fk_userProfile', 'fk_evenement')},
        ),
    ]
