# Generated by Django 2.0.2 on 2018-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IronAgileWebApp', '0002_profile_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_present',
        ),
        migrations.AddField(
            model_name='concerner',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
